language: rust
rust: stable
cache: cargo

before_script:
    - export PATH="$PATH:$HOME/.cargo/bin"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libgpgme11-dev

script:
    - cargo test
    - cargo doc --no-deps
